
version: '2.2'

services:

  porter_client:
    build:
      context: client
    user: nobody:nogroup
    image: cyberdojo/porter-client
    init: true
    container_name: test-porter-client
    read_only: true
    tmpfs: /tmp
    restart: 'no'
    depends_on:
      - porter
    ports:
      - 4598:4598

  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

  porter:
    build:
      context: .
      args:
        - SHA
    user: porter
    image: cyberdojo/porter
    init: true
    container_name: test-porter-server
    read_only: true
    ports:
      - 4517:4517
    tmpfs:
      - /porter:uid=19664,gid=65533
      - /tmp:uid=19664,gid=65533
    restart: 'no'
    depends_on:
      - storer
      - saver

  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

  storer:
    user: storer
    image: cyberdojo/storer
    init: true
    container_name: test-porter-storer
    read_only: true
    ports:
      - 4577:4577
    tmpfs:
      - /usr/src/cyber-dojo/katas:uid=19661,gid=65533
      - /tmp:uid=19661,gid=65533

  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

  saver:
    user: saver
    image: cyberdojo/saver
    init: true
    container_name: test-porter-saver
    read_only: true
    depends_on:
      - mapper
    ports:
      - 4537:4537
    tmpfs:
      - /cyber-dojo:uid=19663,gid=65533
      - /tmp:uid=19663,gid=65533

  # - - - - - - - - - - - - - - - -

  mapper:
    user: nobody
    image: cyberdojo/mapper
    init: true
    container_name: test-porter-mapper
    read_only: true
    ports:
      - 4547:4547
    tmpfs: /tmp
    restart: 'no'
    tmpfs:
      - /porter:uid=65534,gid=65533
      - /tmp:uid=65534,gid=65533
