
version: '2.2'

services:

  porter_client:
    build:
      context: client
    user: nobody:nogroup
    image: cyberdojo/porter-client
    init: true
    container_name: test-porter-client
    read_only: true
    tmpfs: /tmp
    restart: 'no'
    depends_on:
      - porter
    ports:
      - 4598:4598

  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

  porter:
    build:
      context: .
      args:
        - SHA
    user: porter:porter
    image: cyberdojo/porter
    init: true
    container_name: test-porter-server
    read_only: true
    tmpfs:
      - /porter:uid=19664,gid=19664
      - /tmp:uid=19664,gid=19664
    restart: 'no'
    depends_on:
      - storer
      - saver

  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

  storer:
    user: storer:storer
    image: cyberdojo/storer
    init: true
    container_name: test-porter-storer
    read_only: true
    tmpfs:
      - /usr/src/cyber-dojo/katas:uid=19661,gid=19661
      - /tmp:uid=19661,gid=19661

  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

  saver:
    user: saver
    image: cyberdojo/saver
    init: true
    container_name: test-porter-saver
    read_only: true
    tmpfs:
      - /cyber-dojo:uid=19663,gid=19663
      - /tmp:uid=19663,gid=19663
